### ISSUE TITLE
The REI recipe was mistakenly concealed.

### ISSUE THREAD

**Issue by Tki-sor** [AlmostReliable/almostunified#64] opened 2024-01-17 12:02 UTC
### Version

almostunified-forge-1.20.1-0.7.2

### Describe the bug!

RoughlyEnoughItems-12.0.684-forge.jar
gtceu-forge-1.20.1-1.0.19.b.jar

"itemsHidingJeiRei": true
![image](https://github.com/AlmostReliable/almostunified/assets/78548154/d75bb1bb-dca9-4745-b191-114c87faca35)
"itemsHidingJeiRei": false
![image](https://github.com/AlmostReliable/almostunified/assets/78548154/f92bc11f-80ce-4dce-9d1d-54f0d3dd9e5e)

jei-1.20.1-forge-15.2.0.27.jar
"itemsHidingJeiRei": true
![image](https://github.com/AlmostReliable/almostunified/assets/78548154/af04186e-97c1-45c7-b589-85c3806f5e6b)

### Additional Context

Yes

### Modifications

Minimal instance:
![image](https://github.com/AlmostReliable/almostunified/assets/78548154/5af43bdb-51f7-4444-b4c9-56ffeec5d68e)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment] 2024-01-17 14:10
A bit of text with context would have been helpful.

Are you trying to show that with Roughly Enough Items and Almost Unified hiding enabled, the Mixer recipes are hidden but with JEI they are not?

The hiding list JEI and REI receive from our mod are equal and come from the same method. 🤔

**Comment by Tki-sor** [comment] 2024-01-18 02:22
> A bit of text with context would have been helpful.
> 
> Are you trying to show that with Roughly Enough Items and Almost Unified hiding enabled, the Mixer recipes are hidden but with JEI they are not?
> 
> The hiding list JEI and REI receive from our mod are equal and come from the same method. 🤔

That's right, it is like this.
But it's not just Mixin recipe. For example, some recipes for steel plates may also be missing when other tech mods like Mekanism are installed.
I'm not sure exactly how many crafting recipes are missing, as GTCEU has an extensive list of items.

**Comment by Leclowndu93150** [comment] 2024-02-29 14:05
Hi does the fix have any ETA ?

**Comment by rlnt** [comment] 2024-03-03 20:01
I can't reproduce this in my environment. I'd need to see debug logs of what's going on in a world where this happens. If anyone can provide these logs, please join the [Discord](https://discord.com/invite/ThFnwZCyYY) and open a thread.

**Comment by rlnt** [comment] 2024-03-13 20:40
I was finally able to reproduce it in a minimal environment after a long trial and error session.

The issue is not caused by Almost Unified. It can be reproduced without Almost Unified by hiding the same item Almost Unified would via KubeJS. It's either an issue by REI or by GregTech Modern. I am in talks with the respective authors already and I'll submit an issue to their repository as soon as we find the culprit.

Thanks for bringing this up. I can understand that it looked like Almost Unified would be causing this. However, this can't be fixed by us.

**Closed as not planned by rlnt** 2024-03-13 20:40 UTC
Labels: type: bug, type: invalid

**Comment by Leclowndu93150** [comment] 2024-03-13 21:29
you're the goat
