### ISSUE TITLE
Disabled EMI stacks are not functional in recipe transfer handlers

### ISSUE THREAD

**Issue by ffuentesm** [AlmostReliable/almostunified#67] opened 2024-02-23 05:06 UTC
### Version

almostunified-forge-1.20.1-0.8.0

### Describe the bug!

After AU became compatible with EMI, all duplicated items became concealed to the point they became invisible to autocrafting. 
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/c541fe2c-e0d9-4823-bbf6-9f1ba7ebc1a9)
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/238695bc-e2e3-4dff-afb6-0e631dcdf19f)

I can still manually add the items to the grid, but EMI does not recognize them. 
I am just in doubt as if this was intended from the start, as before the EMI compatibility, I still had the recipe unification, but EMI could still recognize items with the same tag as crafting material. As seen in the image above, I could still use copper nuggets from any mod as material. Now only Create Copper Nuggets is "visible" by EMI. 

### Additional Context

Yes

### Modifications

Just a private mod list that I play with, things like Create, IE, Occutims, EMI/JEI, Ice and Fire, JAOPCA, Ars, etc.
Nothing in the technical configs was altered.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment] 2024-02-23 10:07
Hmm, I'd say this is up to EMI to fix. I'll talk to her.

The problem here is that Almost Unified follows the principle that recipes can still accept the whole item tag instead of restricting it to a single item. This prevents non-dominant items from becoming useless in case players are still somehow able to obtain them like from loot chests that are not unified or some special drops.

In JEI/REI, we then hide all items from a tag but the dominant item to avoid confusion when these mods cycle through all the items the tag includes because they are also hidden from the index. The usual scenario should be that these items should not be obtainable anymore so the hiding makes sense.
However, EMI's implementation of the stack hiding/disabling feature has the disadvantage of the transfer handlers not working anymore with disabled stacks. In fact, they treat every tag with a single entry as a normal item stack which is very unfortunate and I don't even know if this can be fixed with the way EMI works.

Edit: in your screenshot (your specific use case), the problem is that your nuggets are not the ones from the preferred one which seems to be Create nuggets, the nuggets in your inventory are a disabled stack so the transfer handler doesn't recognize them anymore because Almost Unified is hiding all nuggets except the Create nuggets so EMI  doesn't treat the input as a tag anymore

**Closed as completed** 2024-03-01 23:55 UTC
Labels: state: completed, type: bug
